{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mesadev",
    "module": "mesalib",
    "version": "1.21.8-fab",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mesalib-1.21.8-fab.jar",
          "url": "mesalib-1.21.8-fab.jar",
          "size": 16332,
          "sha512": "746bfa8a49ecf387e9295aa1dec7757a85fe2af5b881d2b073f88db80ea032c0bdb0bb733d95945a200449914fdf24c5237a406924759948dac866eee8e47e15",
          "sha256": "0dcd029219e6f9fa202f0ad1aa80196459494e94a5337dae221b1353a1152037",
          "sha1": "a80ba2e4d48caaa35d5fbf86198133d4864bcc53",
          "md5": "db83f6744563438fb62048c6402c87c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.129.0+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "mesalib-1.21.8-fab.jar",
          "url": "mesalib-1.21.8-fab.jar",
          "size": 16332,
          "sha512": "746bfa8a49ecf387e9295aa1dec7757a85fe2af5b881d2b073f88db80ea032c0bdb0bb733d95945a200449914fdf24c5237a406924759948dac866eee8e47e15",
          "sha256": "0dcd029219e6f9fa202f0ad1aa80196459494e94a5337dae221b1353a1152037",
          "sha1": "a80ba2e4d48caaa35d5fbf86198133d4864bcc53",
          "md5": "db83f6744563438fb62048c6402c87c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mesalib-1.21.8-fab-sources.jar",
          "url": "mesalib-1.21.8-fab-sources.jar",
          "size": 9931,
          "sha512": "8011ef6ce7b7a41cc67e054cdad33d78576d799969a28e304e26333ec46ec9090257732086ea59f448f4813bf6be81e51433da0627c0312b03d6e134b7a73ca3",
          "sha256": "c3704e97cef92b681ba2551c633c325a516b7f69a03a544a6368e11c5692ccdc",
          "sha1": "66f44b3a988305a10817fe79f16a889fec11f0de",
          "md5": "24354db2ff4a2773004ed996279fd665"
        }
      ]
    }
  ]
}
