{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mesadev.mesalib",
    "module": "mesalib",
    "version": "1.21.8-fab",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mesalib-1.21.8-fab.jar",
          "url": "mesalib-1.21.8-fab.jar",
          "size": 16332,
          "sha512": "746bfa8a49ecf387e9295aa1dec7757a85fe2af5b881d2b073f88db80ea032c0bdb0bb733d95945a200449914fdf24c5237a406924759948dac866eee8e47e15",
          "sha256": "0dcd029219e6f9fa202f0ad1aa80196459494e94a5337dae221b1353a1152037",
          "sha1": "a80ba2e4d48caaa35d5fbf86198133d4864bcc53",
          "md5": "db83f6744563438fb62048c6402c87c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.129.0+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "mesalib-1.21.8-fab.jar",
          "url": "mesalib-1.21.8-fab.jar",
          "size": 16332,
          "sha512": "746bfa8a49ecf387e9295aa1dec7757a85fe2af5b881d2b073f88db80ea032c0bdb0bb733d95945a200449914fdf24c5237a406924759948dac866eee8e47e15",
          "sha256": "0dcd029219e6f9fa202f0ad1aa80196459494e94a5337dae221b1353a1152037",
          "sha1": "a80ba2e4d48caaa35d5fbf86198133d4864bcc53",
          "md5": "db83f6744563438fb62048c6402c87c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mesalib-1.21.8-fab-sources.jar",
          "url": "mesalib-1.21.8-fab-sources.jar",
          "size": 9931,
          "sha512": "d07e68e465f2b11fbd904306daf7e1c88bffb04fb484750f43bc82e4567f47f4f465c77736a7c7337e1806d8ce3d198bee09f6a0d45846a79eb2bb8423d35c3a",
          "sha256": "47f477546aaca52609c34b70d838dc9b5aa51b6f8ae4f6f29b41294e39c1a18b",
          "sha1": "45d20dbc50cf54cc3a50ed0033b5ba936c23c024",
          "md5": "1bf42d3d5cfdd0c98f56014222b614ea"
        }
      ]
    }
  ]
}
