{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mesadev",
    "module": "mesalib",
    "version": "1.21.8f1-fab",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mesalib-1.21.8f1-fab.jar",
          "url": "mesalib-1.21.8f1-fab.jar",
          "size": 16764,
          "sha512": "a8ae1646cc28478ac2ec86c5cac103129111d829acfdc546d9b64b3072d803e7ba30a319a1b4688d50640e6d4e4fb960a5865086317ca9f116291259576a1517",
          "sha256": "cf6b77e5a2234d3f6420cff69d65312f1a821d7fd785f4f3666476717dd13fdd",
          "sha1": "af876e53f01c847f9a06eee0cbaa21f476fdc294",
          "md5": "3d8e981852bb0b4d2347b97df4f7a0d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.129.0+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "mesalib-1.21.8f1-fab.jar",
          "url": "mesalib-1.21.8f1-fab.jar",
          "size": 16764,
          "sha512": "a8ae1646cc28478ac2ec86c5cac103129111d829acfdc546d9b64b3072d803e7ba30a319a1b4688d50640e6d4e4fb960a5865086317ca9f116291259576a1517",
          "sha256": "cf6b77e5a2234d3f6420cff69d65312f1a821d7fd785f4f3666476717dd13fdd",
          "sha1": "af876e53f01c847f9a06eee0cbaa21f476fdc294",
          "md5": "3d8e981852bb0b4d2347b97df4f7a0d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mesalib-1.21.8f1-fab-sources.jar",
          "url": "mesalib-1.21.8f1-fab-sources.jar",
          "size": 10155,
          "sha512": "ae6a4776c1c97a45f42e993687e4efbc2dca7264a14562321f00863e08409d5422351da789961238e97f05a80f06b06edb36fa1c7cdaf6f683634d1efedb8bd1",
          "sha256": "fbc49413b4129725138777566a72a53f15a3e24681208d825ceef7cf709f2e5d",
          "sha1": "2178524c1571ea3a001b5dedc006a9991d59f7e0",
          "md5": "f210db2cacd6e064fcc0308848a76263"
        }
      ]
    }
  ]
}
